from .resistance import resistance
from .vpp import vpp_solve
from .deap_resistance import optimization_deap_resistance
from .deap_appendages import optimization_deap_appendages
from .platypus_resistance import optimization_platypus_resistance
from .parametrization import wl_solve 
from .parametrization import sac_solve 
from .parametrization import keel_solve
from .parametrization import section_solve